# ============================================================
# AXI-Lite RISC-V SoC Verification Platform
# Makefile for linting, simulation, regression, and cleanup
#
# Current milestone:
#   - GPIO AXI-Lite peripheral
#   - cocotb testbench
#   - Verilator simulation
# ============================================================

# ----------------------------
# Project directories
# ----------------------------
PWD_DIR      := $(shell pwd)
RTL_DIR      := $(PWD_DIR)/rtl
TB_DIR       := $(PWD_DIR)/tb
export PYTHONPATH := $(TB_DIR):$(PYTHONPATH)
INC_DIR      := $(PWD_DIR)/include
SCRIPT_DIR   := $(PWD_DIR)/scripts
FIRMWARE_DIR := $(PWD_DIR)/firmware

# ----------------------------
# Tool configuration
# ----------------------------
SIM ?= verilator
TOPLEVEL_LANG ?= verilog

# Default waveform file generated by cocotb/Verilator
WAVE_FILE ?= dump.vcd

# ============================================================
# Windows ModelSim configuration
# ============================================================

MODELSIM_BIN ?= /mnt/c/intelFPGA/20.1/modelsim_ase/win32aloem

VSIM_EXE := $(MODELSIM_BIN)/vsim.exe
VLOG_EXE := $(MODELSIM_BIN)/vlog.exe

MODELSIM_DO        := scripts/modelsim_run.do
MODELSIM_BUILD_DIR := modelsim_build

# ----------------------------
# RTL sources
# ----------------------------
RV32I_PKG_RTL := $(RTL_DIR)/rv32i_pkg.sv
GPIO_RTL          := $(RTL_DIR)/gpio.sv
TIMER_RTL         := $(RTL_DIR)/timer.sv
RAM_RTL           := $(RTL_DIR)/axi_lite_ram.sv
AXI_INTC_RTL      := $(RTL_DIR)/axi_lite_interconnect.sv
AXI_SUBSYSTEM_RTL := $(RTL_DIR)/axi_lite_subsystem.sv
AXI_ASSERT_RTL := $(RTL_DIR)/axi_lite_assertions.sv
# Future files
SOC_TOP_RTL       := $(RTL_DIR)/soc_top.sv
RV32I_CORE_RTL    := $(RTL_DIR)/simple_riscv_core.sv

# ----------------------------
# RV32I RTL sources
# ----------------------------

RV32I_ALU_RTL     := $(RTL_DIR)/rv32i_alu.sv
RV32I_REGFILE_RTL := $(RTL_DIR)/rv32i_regfile.sv
RV32I_DECODER_RTL := $(RTL_DIR)/rv32i_decoder.sv
RV32I_CORE_RTL    := $(RTL_DIR)/simple_riscv_core.sv

# ----------------------------
# ModelSim SystemVerilog testbenches
# ----------------------------

RV32I_ALU_TB     := tb_sv/tb_rv32i_alu.sv
RV32I_REGFILE_TB := tb_sv/tb_rv32i_regfile.sv
RV32I_CORE_TB    := tb_sv/tb_rv32i_core.sv

RV32I_ALU_MSIM_SOURCES := \
	$(RTL_DIR)/rv32i_pkg.sv \
	$(RTL_DIR)/rv32i_alu.sv \
	$(RV32I_ALU_TB)

RV32I_REGFILE_MSIM_SOURCES := \
	$(RTL_DIR)/rv32i_pkg.sv \
	$(RTL_DIR)/rv32i_regfile.sv \
	$(RV32I_REGFILE_TB)

RV32I_CORE_MSIM_SOURCES := \
	$(RTL_DIR)/rv32i_pkg.sv \
	$(RTL_DIR)/rv32i_alu.sv \
	$(RTL_DIR)/rv32i_regfile.sv \
	$(RTL_DIR)/rv32i_decoder.sv \
	$(RTL_DIR)/simple_riscv_core.sv \
	$(RV32I_CORE_TB)

# ----------------------------
# Verilator options
# ----------------------------
VERILATOR_LINT_FLAGS := --lint-only -Wall -I$(INC_DIR)

# Cocotb / Verilator compile options
EXTRA_ARGS += -Wall
EXTRA_ARGS += -I$(INC_DIR)

ifeq ($(SIM),verilator)
EXTRA_ARGS += --trace
EXTRA_ARGS += --trace-structs
EXTRA_ARGS += --assert
endif

# ============================================================
# Default target
# ============================================================

.PHONY: help
help:
	@echo ""
	@echo "AXI-Lite RISC-V SoC Verification Platform"
	@echo "============================================================"
	@echo "Available targets:"
	@echo ""
	@echo "  make lint_gpio        Lint GPIO RTL with Verilator"
	@echo "  make test_gpio        Run GPIO cocotb test"
	@echo "  make waves            Open waveform using GTKWave"
	@echo "  make regression       Run all implemented tests"
	@echo "  make clean            Remove simulation/build outputs"
	@echo "  make status           Show project/tool status"
	@echo ""
	@echo "Future targets:"
	@echo "  make lint_timer       Placeholder for timer lint"
	@echo "  make test_timer       Placeholder for timer test"
	@echo "  make test_axi         Placeholder for AXI interconnect test"
	@echo "  make test_soc         Placeholder for full SoC test"
	@echo ""

# ============================================================
# Status / tool checks
# ============================================================

.PHONY: status
status:
	@echo ""
	@echo "Project directory: $(PWD_DIR)"
	@echo "RTL directory:     $(RTL_DIR)"
	@echo "TB directory:      $(TB_DIR)"
	@echo "Include directory: $(INC_DIR)"
	@echo ""
	@echo "Checking tools..."
	@which verilator || true
	@which gtkwave || true
	@which python3 || true
	@which cocotb-config || true
	@which yosys || true
	@echo ""

.PHONY: check_modelsim
check_modelsim:
	@test -f "$(VSIM_EXE)" || \
		(echo "ERROR: ModelSim was not found at $(VSIM_EXE)" && exit 1)
	@test -f "$(MODELSIM_DO)" || \
		(echo "ERROR: Missing ModelSim script: $(MODELSIM_DO)" && exit 1)
	@case "$$(pwd)" in \
		/mnt/c/*) ;; \
		*) \
			echo "ERROR: Windows ModelSim must run from a Windows-side clone."; \
			echo "Open the repository from /mnt/c/Users/Asus/projects/..."; \
			exit 1; \
			;; \
	esac
	@echo "ModelSim found:"
	@"$(VSIM_EXE)" -version

.PHONY: modelsim_alu
modelsim_alu: check_modelsim
	@"$(VSIM_EXE)" -c -do \
		"set TOP tb_rv32i_alu; \
		 set SOURCES {$(RV32I_ALU_MSIM_SOURCES)}; \
		 set BUILD_DIR {$(MODELSIM_BUILD_DIR)/rv32i_alu}; \
		 set BATCH 1; \
		 do $(MODELSIM_DO)"

.PHONY: modelsim_alu_gui
modelsim_alu_gui: check_modelsim
	@"$(VSIM_EXE)" -do \
		"set TOP tb_rv32i_alu; \
		 set SOURCES {$(RV32I_ALU_MSIM_SOURCES)}; \
		 set BUILD_DIR {$(MODELSIM_BUILD_DIR)/rv32i_alu}; \
		 set BATCH 0; \
		 do $(MODELSIM_DO)"

.PHONY: modelsim_regfile
modelsim_regfile: check_modelsim
	@"$(VSIM_EXE)" -c -do \
		"set TOP tb_rv32i_regfile; \
		 set SOURCES {$(RV32I_REGFILE_MSIM_SOURCES)}; \
		 set BUILD_DIR {$(MODELSIM_BUILD_DIR)/rv32i_regfile}; \
		 set BATCH 1; \
		 do $(MODELSIM_DO)"

.PHONY: modelsim_regfile_gui
modelsim_regfile_gui: check_modelsim
	@"$(VSIM_EXE)" -do \
		"set TOP tb_rv32i_regfile; \
		 set SOURCES {$(RV32I_REGFILE_MSIM_SOURCES)}; \
		 set BUILD_DIR {$(MODELSIM_BUILD_DIR)/rv32i_regfile}; \
		 set BATCH 0; \
		 do $(MODELSIM_DO)"

.PHONY: modelsim_core
modelsim_core: check_modelsim
	@"$(VSIM_EXE)" -c -do \
		"set TOP tb_rv32i_core; \
		 set SOURCES {$(RV32I_CORE_MSIM_SOURCES)}; \
		 set BUILD_DIR {$(MODELSIM_BUILD_DIR)/rv32i_core}; \
		 set BATCH 1; \
		 do $(MODELSIM_DO)"

.PHONY: modelsim_core_gui
modelsim_core_gui: check_modelsim
	@"$(VSIM_EXE)" -do \
		"set TOP tb_rv32i_core; \
		 set SOURCES {$(RV32I_CORE_MSIM_SOURCES)}; \
		 set BUILD_DIR {$(MODELSIM_BUILD_DIR)/rv32i_core}; \
		 set BATCH 0; \
		 do $(MODELSIM_DO)"
# ============================================================
# Lint targets
# ============================================================

.PHONY: lint_gpio
lint_gpio:
	verilator $(VERILATOR_LINT_FLAGS) $(GPIO_RTL)

.PHONY: lint_timer
lint_timer:
	@if [ -f "$(TIMER_RTL)" ]; then \
		verilator $(VERILATOR_LINT_FLAGS) $(TIMER_RTL); \
	else \
		echo "timer.sv not implemented yet."; \
	fi

.PHONY: lint_axi
lint_axi:
	@if [ -f "$(AXI_INTC_RTL)" ]; then \
		verilator $(VERILATOR_LINT_FLAGS) $(AXI_INTC_RTL); \
	else \
		echo "axi_lite_interconnect.sv not implemented yet."; \
	fi

.PHONY: lint_soc
lint_soc:
	@if [ -f "$(SOC_TOP_RTL)" ]; then \
		verilator $(VERILATOR_LINT_FLAGS) \
			-I$(INC_DIR) \
			$(SOC_TOP_RTL) \
			$(AXI_INTC_RTL) \
			$(GPIO_RTL) \
			$(TIMER_RTL) \
			$(RAM_RTL) \
			$(RV32I_CORE_RTL); \
	else \
		echo "soc_top.sv not implemented yet."; \
	fi

.PHONY: lint_subsystem
lint_subsystem:
	verilator $(VERILATOR_LINT_FLAGS) \
		$(AXI_SUBSYSTEM_RTL) \
		$(AXI_INTC_RTL) \
		$(RAM_RTL) \
		$(GPIO_RTL) \
		$(TIMER_RTL) \
		$(AXI_ASSERT_RTL)

.PHONY: lint_ram
lint_ram:
	verilator $(VERILATOR_LINT_FLAGS) $(RAM_RTL)


.PHONY: lint
lint: lint_gpio lint_timer lint_ram lint_subsystem
	@echo "Implemented lint checks completed."

# ============================================================
# Cocotb simulation targets
# ============================================================

.PHONY: test_gpio
test_gpio:
	$(MAKE) sim \
		SIM=$(SIM) \
		TOPLEVEL_LANG=$(TOPLEVEL_LANG) \
		TOPLEVEL=gpio \
		COCOTB_TEST_MODULES=test_gpio \
		VERILOG_SOURCES="$(GPIO_RTL)" \
		SOURCES="$(GPIO_RTL)" \
		EXTRA_ARGS="$(EXTRA_ARGS)" \
		SIM_BUILD=sim_build/gpio 

.PHONY: test_timer
test_timer:
	@if [ -f "$(TIMER_RTL)" ] && [ -f "$(TB_DIR)/test_timer.py" ]; then \
		$(MAKE) sim \
			SIM=$(SIM) \
			TOPLEVEL_LANG=$(TOPLEVEL_LANG) \
			TOPLEVEL=timer \
			COCOTB_TEST_MODULES=test_timer \
			VERILOG_SOURCES="$(TIMER_RTL)" \
			SOURCES="$(TIMER_RTL)" \
			EXTRA_ARGS="$(EXTRA_ARGS)" \
			SIM_BUILD=sim_build/timer; \
	else \
		echo "Timer RTL/testbench not implemented yet."; \
	fi

.PHONY: test_ram
test_ram:
	@if [ -f "$(RAM_RTL)" ] && [ -f "$(TB_DIR)/test_axi_lite_ram.py" ]; then \
		$(MAKE) sim \
			SIM=$(SIM) \
			TOPLEVEL_LANG=$(TOPLEVEL_LANG) \
			TOPLEVEL=axi_lite_ram \
			COCOTB_TEST_MODULES=test_axi_lite_ram \
			VERILOG_SOURCES="$(RAM_RTL)" \
			SOURCES="$(RAM_RTL)" \
			EXTRA_ARGS="$(EXTRA_ARGS)" \
			SIM_BUILD=sim_build/ram; \
	else \
		echo "AXI-Lite RAM RTL/testbench not implemented yet."; \
	fi

.PHONY: test_axi
test_axi:
	@if [ -f "$(AXI_INTC_RTL)" ] && [ -f "$(TB_DIR)/test_axi_lite.py" ]; then \
		$(MAKE) sim \
			SIM=$(SIM) \
			TOPLEVEL_LANG=$(TOPLEVEL_LANG) \
			TOPLEVEL=axi_lite_interconnect \
			COCOTB_TEST_MODULES=test_axi_lite \
			VERILOG_SOURCES="$(AXI_INTC_RTL) $(GPIO_RTL) $(TIMER_RTL)" \
			EXTRA_ARGS="$(EXTRA_ARGS)" \
			SIM_BUILD=sim_build/axi; \
	else \
		echo "AXI interconnect RTL/testbench not implemented yet."; \
	fi

.PHONY: test_soc
test_soc:
	@if [ -f "$(SOC_TOP_RTL)" ] && [ -f "$(TB_DIR)/test_soc_program.py" ]; then \
		$(MAKE) sim \
			SIM=$(SIM) \
			TOPLEVEL_LANG=$(TOPLEVEL_LANG) \
			TOPLEVEL=soc_top \
			COCOTB_TEST_MODULES=test_soc_program \
			VERILOG_SOURCES="$(SOC_TOP_RTL) $(RV32I_CORE_RTL) $(AXI_INTC_RTL) $(GPIO_RTL) $(TIMER_RTL) $(RAM_RTL)" \
			EXTRA_ARGS="$(EXTRA_ARGS)" \
			SIM_BUILD=sim_build/soc; \
	else \
		echo "SoC RTL/testbench not implemented yet."; \
	fi

.PHONY: test_subsystem
test_subsystem:
	$(MAKE) sim \
		SIM=$(SIM) \
		TOPLEVEL_LANG=$(TOPLEVEL_LANG) \
		TOPLEVEL=axi_lite_subsystem \
		COCOTB_TEST_MODULES=test_axi_lite_subsystem \
		VERILOG_SOURCES="$(AXI_SUBSYSTEM_RTL) $(AXI_INTC_RTL) $(RAM_RTL) $(GPIO_RTL) $(TIMER_RTL) $(AXI_ASSERT_RTL)" \
		SOURCES="$(AXI_SUBSYSTEM_RTL) $(AXI_INTC_RTL) $(RAM_RTL) $(GPIO_RTL) $(TIMER_RTL) $(AXI_ASSERT_RTL)" \
		EXTRA_ARGS="$(EXTRA_ARGS)" \
		SIM_BUILD=sim_build/subsystem

# ============================================================
# Regression
# ============================================================

.PHONY: regression
regression:
	$(MAKE) clean
	$(MAKE) lint
	$(MAKE) test_gpio
	$(MAKE) test_timer
	$(MAKE) test_ram
	$(MAKE) test_subsystem
	@echo ""
	@echo "============================================================"
	@echo "Regression completed."
	@echo "Implemented tests passed."
	@echo "============================================================"
# ============================================================
# Waveform viewing
# ============================================================

.PHONY: waves
waves:
	@if [ -f "$(WAVE_FILE)" ]; then \
		gtkwave $(WAVE_FILE); \
	elif [ -f "dump.fst" ]; then \
		gtkwave dump.fst; \
	else \
		echo "No waveform file found. Run make test_gpio first."; \
	fi

# ============================================================
# Yosys synthesis check
# ============================================================

.PHONY: synth_gpio
synth_gpio:
	yosys -p "read_verilog -sv -I$(INC_DIR) $(GPIO_RTL); synth; stat"

# ============================================================
# Cleanup
# ============================================================

.PHONY: clean
clean::
	rm -rf sim_build
	rm -rf obj_dir
	rm -rf modelsim_build
	rm -rf work
	rm -rf __pycache__
	rm -rf tb/__pycache__
	rm -rf .pytest_cache
	rm -f results.xml
	rm -f dump.vcd
	rm -f dump.fst
	rm -f dump.lxt
	rm -f *.vcd
	rm -f *.fst
	rm -f *.lxt
	rm -f *.log
	rm -f *.xml
	rm -f transcript
	rm -f modelsim.ini
	rm -f vsim.wlf
	rm -f *.jou
	rm -f *.wdb



# ============================================================
# Include cocotb simulator Makefile for cocotb sim/results targets
# ============================================================

ifneq ($(filter sim results.xml,$(MAKECMDGOALS)),)
include $(shell cocotb-config --makefiles)/Makefile.sim
endif